### PR TITLE
add a delay for nextVictim

### LINKED ISSUE #11: API limit hit on 30+ urls in file
Query API limit is hit if file contain 30+ URLs. Since Query API limit is related to no more than 10 requests per second limit, script in extension should not query Google APIs more frequently than 9 requests per second. The easiest way may be add some wait 1s parameter after posting URL to removal.

### PR DESCRIPTION
**Pull request by jpmckearin**
fixes #11 

This keeps us from hitting Google's API limits.

### CODE REVIEW

**Comment by noitcudni** [comment]
Thanks. I'll test it out this weekend. I tried hitting Google's limits by removing 100+ urls but was unable to. It's probably wise to add a timer anyway.

**Comment by jpmckearin** [comment]
I think it will only realistically happen if something goes wrong, such as not matching the scheme (http/https) of the property. Regardless, each nextVictim call takes just under a second anyways so this is a nice fallback.

**Comment by noitcudni** [comment]
Thanks for the PR. Chrome extension and/or browser supports the newer javascript syntax? I just tested it and worked fine, so I suppose the answer is yes.

**Comment by jpmckearin** [comment]
@noitcudni yeah we are good.

**Pull request merged**
